### ISSUE TITLE
Non-existing user entry with SAML SSO leads to login loop

### ISSUE THREAD

**Issue by xenji** [open-metadata/OpenMetadata#16076]
**Affected module**
Probably UI and backend

**Describe the bug**
When I enable SSO via Okta and try to access the application the first time, I end up on the "Sign in with SSO screen". After pressing the button, I am redirected back to the same screen instead of getting logged in.

**To Reproduce**
* Create a SAML authentication (we use Okta)
* Go to the app the first time via the Okta tile (with no record of this user in the DB)
* You will end up on the "Sign in with SSO screen" (I think because of the 404)
* You can endlessly loop on the sign-in screen (sign in -> okta -> sign in)

Disabling the browser cache in the developer console leads to the correct behavior and displays the initial user creation form. Any further attempts to log in are directly successful. From a pure logical perspective, the issue seems to be at the decision point for showing the user creation form.

**Expected behavior**
User creation form is displayed directly without any loops.

**Version:**
 - OpenMetadata version: 1.3.3

**Additional context**
* Okta SAML
* EKS, ALB Ingress, ACM for SSL
* There has been some discussion about it here: https://openmetadata.slack.com/archives/C02B6955S4S/p1714380589041649

**Comment by xenji** [comment]
I might be able to share a video recording of this, but only for a limited audience. Please get in touch if you consider this helpful for your analysis.

**Comment by Sachin-chaurasiya** [comment]
Hello @xenji , thanks for filing a ticket, this issue has been fixed and will be available with the 1.4 release.

**Comment by xenji** [comment]
I've just upgraded the deployment to the 1.4.0 version and the issue is still present.

**Comment by golsonallen** [comment]
Were you able to find a fix? Facing this issue on Azure SSO

**Comment by milesgranger** [comment]
Also interested - same thing with Azure in v1.9.0
