### ISSUE TITLE
No relations for clickhouse views (and materialized) in lineage

### ISSUE THREAD

**Issue by mrkoloev** [open-metadata/OpenMetadata#17574]
**Affected module**
Lineage view for Clickhouse

**Describe the bug**
No relations for clickhouse views (and materialized views) in lineage

**To Reproduce**
1) Ingest metadata from clickhouse.
2) choose view (or materialized view) in the list of ch table
3) click lineage tab

Screenshots or steps to reproduce
![mv_ch](https://github.com/user-attachments/assets/05e6e274-cf17-4f26-b402-3e8fab9e78c5)

**Expected behavior**
I expect the UI to show me the relation from the materialized view schema definition. 

**Version:**
 - OS: macOS Ventura 13.5
 - Python version: 3.11.7
 - OpenMetadata version: 1.4.8
 - OpenMetadata Ingestion package version: openmetadata-ingestion[docker]==1.4.8.

**Additional context**
Docker version 25.0.2
Docker Compose version v2.24.3-desktop.1

**Comment by LuanAraldi** [comment]
I believe that this is probably because OpenMetadata is not identifying that some queries on the query log of clickhouse have the schema prefix attached to the tables for some queries, I've got this from the Airflow DAG debug log when trying that
```
WARNING: Table entity [schema.table_test] not found in OpenMetadata
```
Even though `table_test` is a table entity that I have the metadata of, I don't think it is making the relation that `schema.table_test` is the same thing as `table_test`

**Comment by ulixius9** [comment]
This issue should be fixed with the latest release

**Comment by agusosimani** [comment]
@ulixius9 Lineage for Materialized Views is still not available

**Comment by ulixius9** [comment]
Hey @agusosimani can you share an example, it should be supported

**Comment by agusosimani** [comment]
@ulixius9 
None of my materialized views have downstream lineage.

<img width="323" height="436" alt="Image" src="https://github.com/user-attachments/assets/78b3cb2b-33be-4427-9953-6f3e3a16fde7" />

I'm on version 1.11.7

**Comment by harshach** [comment]
@agusosimani would you be open to share debug logs, we can do this over slack(https://slack.open-metadata.org)
