### ISSUE TITLE
Can't run table diffs on snowflake when using private key authentication

### ISSUE THREAD

**Issue by julesmga** [open-metadata/OpenMetadata#19175]
**Affected module**
Ingestion Framework

**Describe the bug**
Trying to set up a table diff between 2 snowflake accounts, both using private key authentication. The test pipeline fails, complaining password is empty.

**To Reproduce**
* Set up 2 snowflake databases with private key authentication
* Set up a table diff between tables across both databases
*  See following log

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 186, in run_validation
    return self._run()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 214, in _run
    result = self.get_column_diff()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 498, in get_column_diff
    changed = self.get_incomparable_columns()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 262, in get_incomparable_columns
    table1 = data_diff.connect_to_table(
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/__init__.py", line 35, in connect_to_table
    db: Database = connect(db_info, thread_count=thread_count)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/_connect.py", line 282, in __call__
    conn = self.connect_to_uri(db_conf, thread_count, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/_connect.py", line 211, in connect_to_uri
    db = cls(**kw, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/snowflake.py", line 164, in __init__
    self._conn = snowflake.connector.connect(schema=f'"{schema}"', **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect
    self.__config(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config
    Error.errorhandler_wrapper(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 251006: Password is empty
```

**Expected behavior**
The table diff test should support private key authentication like other ingestions.

**Version:**
 - OS: Debian 12
 - Python version: 3.10
 - OpenMetadata version: 1.6.1
 - OpenMetadata Ingestion package version: 1.6.1

**Additional context**
Running OpenMetadata via docker-compose.

**Comment by harshach** [comment]
@TeddyCr should this be closed, looks like we merged in a PR

**Comment by pmbrull** [comment]
solved https://github.com/open-metadata/OpenMetadata/pull/19734

**Comment by julesmga** [comment]
@pmbrull Looks like this is not fully fixed yet:

```
[2025-06-16T08:31:41.546+0000] {tableDiff.py:202} ERROR - Unexpected error while running the table diff test: Cannot use password and key at the same time
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 186, in run_validation
    return self._run()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 214, in _run
    result = self.get_column_diff()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 522, in get_column_diff
    changed = self.get_incomparable_columns()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py", line 262, in get_incomparable_columns
    table1 = data_diff.connect_to_table(
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/__init__.py", line 37, in connect_to_table
    db: Database = connect(db_info, thread_count=thread_count, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/_connect.py", line 282, in __call__
    conn = self.connect_to_uri(db_conf, thread_count, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/_connect.py", line 211, in connect_to_uri
    db = cls(**kw, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/data_diff/databases/snowflake.py", line 147, in __init__
    raise ConnectError("Cannot use password and key at the same time")
data_diff.databases.base.ConnectError: Cannot use password and key at the same time
```
I only have a key and the key password set in the database connection tab, the regular password is definitely empty, so I'm not sure where this is coming from.

Should I open a new issue?
