### ISSUE TITLE
500 error on Home feed with “JSON parsing failed” banner

### ISSUE THREAD

**Issue by henok20** [open-metadata/OpenMetadata#22941]
**Affected module**
UI & Backend (Feed API)

**Describe the bug**
When loading the Home page, the Activity Feed section for type=Conversation fails with a 500 Internal

Server Error.
The UI displays a red toast banner:

JSON parsing failed with message [Failed to process JSON].

This results in the feed not rendering and “No Recent Activity” being shown.

**To Reproduce**

1. Sign in to OpenMetadata UI.
2. Land on the Home page.
3. Observe a red toast banner and empty feed.
4. In DevTools → Network, see:

GET /api/v1/feed?type=Conversation&limit=25 → 500 Internal Server Error
content-type: application/json
server: istio-envoy
x-envoy-upstream-service-time: 47

**Expected behavior**

- The GET /api/v1/feed?type=Conversation request should return 200 OK with a valid JSON payload.
- The UI should display recent “Conversation” feed items without any JSON parse error.

**Version:**
 - OS: macOS (client)
 - Python version:
 - OpenMetadata version: 1.9.0, 1.9.1
 - OpenMetadata Ingestion package version: N/A

**Additional context**

- The 500 likely returns a non-JSON or invalid JSON body, causing the UI to show a parsing error instead of a friendly message.
- Deployment runs behind Istio/Envoy in Kubernetes.

**Comment by harshach** [comment]
@henok20 this should be fixed in the 1.9.1 please make sure you are running migrations

**Comment by henok20** [comment]
@harshach still seeing the issue with 1.9.1 version. 

<img width="2204" height="362" alt="Image" src="https://github.com/user-attachments/assets/794b40a4-6279-4a6d-a698-e6ca423d765e" />

**Comment by harshach** [comment]
cc @sonika-shah please follow-up here

**Comment by androchentw** [comment]
This issue may be related to the [v1.9.0 release Breaking Changes](https://github.com/open-metadata/OpenMetadata/releases/tag/1.9.0-release).

According to the release notes:

Multi-domain Support
All entities now support multiple domains. The domain field has been renamed to domains and is now modeled as a list of domains instead of a single domain.

If you are using the API or SDK, you will need to update your code to reference the new domains field instead of domain. Additionally, the patch_domain implementation has been updated with a new signature to support the domains field.

**Comment by sonika-shah** [comment]
hi @androchentw ,can you confirm if you executed the migrations  `./bootstrap/openmetadata-ops.sh migrate` , before starting the OMD server

**Comment by sonika-shah** [comment]
**@henok20 I’d like to understand more about your OMD setup. Do you have multiple pods running? If so, please run the migrations with the `--force` option:**

```bash
./bootstrap/openmetadata-ops.sh migrate --force
```

**Comment by sonika-shah** [comment]
@henok20 If running with `--force` doesn’t fix the issue, please connect on the OpenMetadata Slack (#support channel): [https://join.slack.com/t/openmetadata/shared\_invite/zt-3bemoycn6-LVqZ77b2KxS1CZM9EyiwYw](https://join.slack.com/t/openmetadata/shared_invite/zt-3bemoycn6-LVqZ77b2KxS1CZM9EyiwYw). 

We can discuss it further and work with you to get it resolved.

**Comment by ayush-shah** [comment]
This can also be due to search indexing
Can you try 
```
batch size: 5
payloadSize: 94371840
producer: 5
consumer: 5
recreate: True
queueSize: 75
concurrent: 100
```

and trigger reindexing

**Comment by henok20** [comment]
> [@henok20](https://github.com/henok20) If running with `--force` doesn’t fix the issue, please connect on the OpenMetadata Slack (#support channel): https://join.slack.com/t/openmetadata/shared_invite/zt-3bemoycn6-LVqZ77b2KxS1CZM9EyiwYw.
> 
> We can discuss it further and work with you to get it resolved.

I tried running with `--force`, but the issue still persists. I’ll join the #support channel on Slack so we can discuss further.

**Comment by sonika-shah** [comment]
hi @henok20 please link the slack thread here, not able to find your conversation in #support channel

**Comment by henok20** [comment]
> hi [@henok20](https://github.com/henok20) please link the slack thread here, not able to find your conversation in #support channel

here is the link for the slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1755270965386399

**Comment by ayush-shah** [comment]
Since this is being supported from Slack, closing this, if anything, we can reopen the ticket

**Comment by romanqqpr** [comment]
what is the resolution of this problem? i have same problem on 1.12.11 version, after upgrade from 1.5.13

**Comment by ayush-shah** [comment]
@romanqqpr can you join [OpenMetadata slack](https://slack.open-metadata.org) 

we can take it forward from there, also please upgrade to 1.13, modify the search indexing configuration to have lower batch size, see if your elasticsearch / opensearch resources are good, it should be fixed after that, but if not, please open a thread in OSS Slack.

Thanks,
Ayush

**Comment by romanqqpr** [comment]
> [@romanqqpr](https://github.com/romanqqpr) can you join [OpenMetadata slack](https://slack.open-metadata.org)
> 
> we can take it forward from there, also please upgrade to 1.13, modify the search indexing configuration to have lower batch size, see if your elasticsearch / opensearch resources are good, it should be fixed after that, but if not, please open a thread in OSS Slack.
> 
> Thanks, Ayush

Hello, thank you. Already fix it, just restore my db backup, stop openmetadata server and run all migrations again. After that was updated correctly to 1.12.12
