### ISSUE TITLE
Login UI takes much time with Google SSO

### ISSUE THREAD

**Issue by ekremgurdal** [open-metadata/OpenMetadata#23056]
**Affected module**
UI is affected.

**Describe the bug**
We are using Google SSO for login. When try to re-login, It takes much time to load login UI.  

**To Reproduce**

Screen recordings are attached.

**Expected behavior**
max 3-4 seconds to load.

**Version:**
1.8.7  k8s deployment

https://github.com/user-attachments/assets/c3bcabd1-b11d-4dec-97bf-3e172ea453f9

https://github.com/user-attachments/assets/731283fc-755f-4c32-8a4e-39f6b7b708dd

**Comment by harshach** [comment]
@chirag-madlani ^

**Comment by chirag-madlani** [comment]
Just to add a bit, it's happening when OM is trying to restore previous session. we need to improve session restore behaviour bit smooth so that it doesn't look like app is taking time to load

**Comment by shrushti2000** [comment]
This is addressed in SSO Configuration from UI PR changes.

**Comment by ghost** [comment]
> This is addressed in SSO Configuration from UI PR changes.

@shrushti2000 What do you mean? what PR? is it merged?  Do you mean #23546?

I still see this in OM 1.10.1

**Comment by ghost** [comment]
I see **CORS Errors** from accounts.google.com in the browser which I believe it may be related to this problem. 

The Network tab in the browser shows that there are requests (originated from javascript I believe) to https://accounts.google.com


<img width="881" height="41" alt="Image" src="https://github.com/user-attachments/assets/fa4f287e-b026-4212-b195-f51050fe2111" />

on the browser console we see the same thing: 

```
Access to manifest at 'https://accounts.google.com/o/oauth2/v2/auth?client_id=xxxx.apps.googleusercontent.com...' (redirected from 'https://openmetadata.xxxx.dev/manifest.json') from origin 'https://openmetadata.xxxx.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

These errored requests are repeated  continuously as long as the `https://openmetadata.xxxx.dev/signin` page is opened. 

The domain `openmetadata.xxxx.dev` is in the "Authorized Javascript Origins" and on the "Redirect URIs" configuration of the client on the google side.

**Comment by chirag-madlani** [comment]
@ecerulm-st CORS error seems different issue, please check with slack support on config to get it fixed.
Above issue was specific to refresh call which leads to access the application instead redirect them to /signin page

@ekremgurdal Please validate this issue with 1.10.2 and let me know if you still face the issue

**Comment by ghost** [comment]
@chirag-madlani With OpenMetadata 1.10.5 it still takes 20 seconds for the "Welcome to OpenMetadata / Sign in with Google" to appear.

**Comment by ekremgurdal** [comment]
@chirag-madlani We upgraded OM to 1.10.8 yesterday. Currently it's loading around 2.5 seconds. Thanks for the fix.
