### ISSUE TITLE
Column Profile Not Visible in the UI

### ISSUE THREAD

**Issue by ronaldmego** [open-metadata/OpenMetadata#23542]
**Affected module**
Backend / API - Column profiling data is stored but not accessible through UI/API endpoints

**Describe the bug**
Column profiling tasks execute successfully and store data in `profiler_data_time_series` table, but column-level metrics are not visible in the UI. The UI shows "No Profile" status for all columns despite successful profiler execution and data storage in PostgreSQL.

**To Reproduce**

1. Configure BigQuery connector with profiling enabled
2. Create/run profiler pipeline for a table (e.g., `telco-data.galacticaia-main-project.telco_tracking_raw.ar_info_trckng_fct`)
3. Verify profiler task completes successfully in Airflow logs
4. Navigate to table Column Profile tab in OpenMetadata UI
5. Observe all columns show "No Profile" status

**Database investigation reveals:**
```sql
-- Profiling data exists in time series table
SELECT COUNT(*) FROM profiler_data_time_series; -- Returns 14,003 records

-- But column profiles are NULL in table entity
SELECT json->'columnProfile' FROM profiler_data_time_series 
WHERE entityFQNHash = 'table_hash'; -- Returns NULL

-- Table entity columns show no profile data
SELECT col->>'name', 
       CASE WHEN col->'profile' IS NOT NULL THEN 'Has Profile' ELSE 'No Profile' END
FROM table_entity, jsonb_array_elements(json->'columns') as col
WHERE json->>'fullyQualifiedName' LIKE '%table_name%'; -- All show "No Profile"
Expected behavior
Column profiling metrics (null count, unique count, distinct count, etc.) should be visible in the UI Column Profile tab after successful profiler execution.
Screenshots

UI shows "No Profile" for all 123 columns
Airflow logs show successful profiler task completion
PostgreSQL confirms 14,003+ profiling records stored

Version:

OS: Linux (Docker containers)
Python version: 3.10 (Docker image default)
OpenMetadata version: 1.8.8
OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.8.8

Additional context
This appears identical to issue #22835 where profiling data exists but UI/API can't retrieve it. Airflow logs show successful profiler execution (some tasks 60+ minutes duration), and PostgreSQL confirms data storage, but there's a disconnect between data persistence and UI/API retrieval.
Airflow Configuration:

Database: postgresql+psycopg2://airflow_user:airflow_pass@postgresql:5432/airflow_db
Profiler tasks show SUCCESS status but column-level data doesn't sync to table_entity JSON

Database Evidence:

profiler_data_time_series: 14,003+ records
data_quality_data_time_series: 88 records
Table entity json->'columnProfile': NULL for all records

This suggests profiling execution works but column-level metric serialization/persistence to table entity fails, causing UI to display "No Profile" status.

This was reported previusly via Slack Support Channel https://openmetadata.slack.com/archives/C02B6955S4S/p1756850484191999

<img width="2121" height="1132" alt="Image" src="https://github.com/user-attachments/assets/7c9a02b7-6d73-40ed-aa9e-5c3b3d4960f6" />

**Comment by harshach** [comment]
@ronaldmego can you post the screenshot of it? and see the api responses in the browser console?

**Comment by ronaldmego** [comment]
Hello @harshach , Sure, I’m attaching the required information. Please let me know if you need any additional details, and I’ll be happy to provide them.

<img width="2121" height="1132" alt="Image" src="https://github.com/user-attachments/assets/d647f203-3ddf-4436-b4a8-d7847759f8a5" />
<img width="2559" height="1436" alt="Image" src="https://github.com/user-attachments/assets/43e7692e-23cb-44c5-a54e-a77161a508cc" />
<img width="2559" height="1431" alt="Image" src="https://github.com/user-attachments/assets/d3921acc-17ab-418e-a5d4-f479ba24f682" />
<img width="2559" height="1438" alt="Image" src="https://github.com/user-attachments/assets/73f55d47-5103-4ac9-aa50-4b4bebf73843" />

**Comment by ShaileshParmar11** [comment]
Hello @ronaldmego, I can see information visible in the `Arrangement Key` column, and there are value counts available for all the columns. Could you please check the details page for the `Arrangement Key` column? You’ll be able to see a metric chart there.

**Comment by ShaileshParmar11** [comment]
Hello @ronaldmego is this resolved at your end?

**Comment by ShaileshParmar11** [comment]
As per the screenshot shared by @ronaldmego, we can see the profiler is visible.
Please reopen this issue if you face any issues or have any doubts

**Comment by ronaldmego** [comment]
As I mentioned before, and as we also discussed on Slack, only some columns are visible while others are not. I believe this is a bug, since it is not resolved on my end. I will try other ways to get the profile of my columns. Thank you.
