### ISSUE TITLE
Downstream Column Level Impact Analysis only shows first node depth

### ISSUE THREAD

**Issue by steven13cooper** [open-metadata/OpenMetadata#23809]
**Affected module**
Column Level Impact Analysis

**Describe the bug**
In the lineage view for a table I can see multiple node depths for a column. On the impact analysis you can see the same at an asset level but at the column level only the first depth is shown. However going back the opposite direction looking upstream from the downstream asset the column level impact analysis is as expected.

**To Reproduce**

<img width="1440" height="503" alt="Image" src="https://github.com/user-attachments/assets/418ec435-c844-41f1-ae7f-b7605339488e" />

<img width="1618" height="247" alt="Image" src="https://github.com/user-attachments/assets/eb6a3f44-1c32-42e6-a065-f0c1e11a2559" />

Missing columns for node depth 2

<img width="1625" height="835" alt="Image" src="https://github.com/user-attachments/assets/0ae02a54-69f1-4e23-9e50-7046f4bdbeb2" />

Going upstream from the downstream asset is fine though

<img width="1622" height="813" alt="Image" src="https://github.com/user-attachments/assets/552ab7d9-de4c-4e07-8a02-ca77c7a4df6f" />

**Expected behavior**
Column level impact analysis downstream shows the columns past a node depth of 1

**Version:**
 - OpenMetadata version: 1.10.0

**Additional context**

**Comment by chirag-madlani** [comment]
@steven13cooper Have you check the node depth filter? That should solve this thanks

**Comment by steven13cooper** [comment]
Hi @chirag-madlani, yes I have. Currently running 1.10.3.

Node depth is set to 3 for both upstream and downstream. Still have the same issue where looking at the downstream with 'Impact On' set to Table I can see all the downstream assets fine to all node depths but as soon as I change the 'Impact On' to Column it only shows the columns for the first node depth. If I go to the table at the first node depth and go to the same view, then I can see the downstream columns for the table at the second node depth so that information is there, but I expect to see all columns for all node depths in the column view past the first node depth.

There is also another bug where if I change tab from downstream to upstream in the Column view the metric for number of columns in downstream displays as 0.

![Image](https://github.com/user-attachments/assets/709e9e30-4104-49b2-8bc8-a430fb0d5aa8)
![Image](https://github.com/user-attachments/assets/d24c02ce-a30e-480f-85ff-7bfd0643b005)

**Comment by chirag-madlani** [comment]
@steven13cooper Kindly use slack to resolve it
https://open-metadata.org/

**Comment by chirag-madlani** [comment]
> There is also another bug where if I change tab from downstream to upstream in the Column view the metric for number of columns in downstream displays as 0.

This will be fixed in 1.11.1
