### ISSUE TITLE
Lineage issue with PowerBI and Databricks UC Connector

### ISSUE THREAD

**Issue by harsha13122001** [open-metadata/OpenMetadata#24059]
This is regarding the PowerBI + Databricks UC connector where the lineage is formed when the table names are exactly the same in both services but if the reports are built on the same tables but with different business names the lineage is not forming.

**Describe the solution you'd like**
I would like if the OpenMetadata Tool can recognize the business names scenario and form the lineage between powerbi and databricks services when even business names of the tables are cosidered in powerbi.

**Comment by finite1** [comment]
We also have an issue with the lineage between UC and PBI, where it creates it for some tables but not for all. However, we haven't fully figured out the reason. I want to verify if this is the issue we're having, would you mind explaining what you mean with different business names? How would I investigate this? @harsha13122001 


We figured it out. Yes we are also interested in fixing this. We face the same issue.

**Comment by smga3000** [comment]
Thanks @harsha13122001 for the report, it should be resolved soon. In the meantime, the best way to keep track of all the latest updates is by bookmarking [OpenMetadata](https://github.com/open-metadata/OpenMetadata) with a star! And, if you haven’t already, I'd like to invite you to join our upcoming virtual community meetup next Wednesday. We’ll be sharing the OMD Q1 roadmap along with a community spotlight featuring real-world use cases from Wix. Hope to see you there!

**Comment by harshsoni2024** [comment]
@finite1 , @harsha13122001 could you please test lineage with databricks & uc catalogs with latest versions of OpenMetadata i.e. 1.11.8 ?

**Comment by finite1** [comment]
@harshsoni2024 We still don't get lineage from PBI to UC for dashboards where the table was renamed in the data model, tested with 1.11.9
