### ISSUE TITLE
Tables ingested via CLI do not appear in "Explore" section of the UI

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#2456]
Hello, 

I have a script set up which ingests 3 databases.  As of 0.8.0, after running the script, I can see the results if I drill into the services from the "Services" page, but I cannot see the results in the "Explore" menu or via the searchbar like expected.

https://user-images.githubusercontent.com/42276144/151194638-5beb333c-6c2e-4481-822a-7cbd6eb5df14.mov

```
pip list | grep openmetadata
openmetadata-ingestion      0.8.1
openmetadata-ingestion-core 0.8.0
```

```
docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                    PORTS                                                                                  NAMES
5d9e16f5709e   openmetadata/ingestion:0.8.0                           "./ingestion_depende…"   39 minutes ago   Up 39 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              openmetadata_ingestion
b95e59b49989   openmetadata/server:0.8.0                              "./openmetadata-star…"   39 minutes ago   Up 39 minutes             3306/tcp, 9200/tcp, 9300/tcp, 0.0.0.0:8585->8585/tcp, :::8585->8585/tcp                openmetadata_server
8fefd62a575b   openmetadata/db:0.8.0                                  "/entrypoint.sh mysq…"   39 minutes ago   Up 39 minutes (healthy)   3306/tcp, 33060-33061/tcp                                                              openmetadata_mysql
aa1b628b9555   docker.elastic.co/elasticsearch/elasticsearch:7.10.2   "/tini -- /usr/local…"   18 hours ago     Up 39 minutes             0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9300->9300/tcp   openmetadata_elasticsearch
```

**Comment by harshach** [comment]
Thanks for reporting this @juliarvalenti .
@akash-jain-10 looks like we have old config  https://github.com/open-metadata/OpenMetadata/blob/main/docker/metadata/openmetadata.yaml#L122 
we need to remove that line and test it once by ingesting from redshift

**Comment by akash-jain-10** [comment]
Hello @juliarvalenti , We have fixed this issue and updated docker images with tag `0.8.0`. Please test out once again with latest docker images and let us know.

**Comment by juliarvalenti** [comment]
Hi Akash, 

I'm still receiving this issue here on the latest OpenMetadata master branch.

`docker ps`
```
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED         STATUS                   PORTS                                                                                  NAMES
a9547268e65f   openmetadata/ingestion:0.8.0                           "./ingestion_depende…"   4 minutes ago   Up 4 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              openmetadata_ingestion
f640a6fa431b   openmetadata/server:0.8.0                              "./openmetadata-star…"   4 minutes ago   Up 3 minutes             3306/tcp, 9200/tcp, 9300/tcp, 0.0.0.0:8585->8585/tcp, :::8585->8585/tcp                openmetadata_server
24a0fb2123e8   openmetadata/db:0.8.0                                  "/entrypoint.sh mysq…"   4 minutes ago   Up 4 minutes (healthy)   3306/tcp, 33060-33061/tcp                                                              openmetadata_mysql
4b97d62c86f3   docker.elastic.co/elasticsearch/elasticsearch:7.10.2   "/tini -- /usr/local…"   4 minutes ago   Up 4 minutes             0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9300->9300/tcp   openmetadata_elasticsearch
```

Ingestion logs: 
[openmetadata-logs-02-02-2022.txt](https://github.com/open-metadata/OpenMetadata/files/7988390/openmetadata-logs-02-02-2022.txt)

"Explore" UI still shows only the shopify tables that come with OpenMetadata, and not the ones that were ingested.

**Comment by juliarvalenti** [comment]
Here is a screenshot showing that airport cannot be found in the search.

![Screen Shot 2022-02-02 at 11 42 33 AM](https://user-images.githubusercontent.com/42276144/152197905-921b8c18-b6b1-4d92-93c3-8e5b8587f4fd.png)

Here is a screenshot showing that it exists in the "Services" ui

![Screen Shot 2022-02-02 at 11 42 48 AM](https://user-images.githubusercontent.com/42276144/152198045-cf0e16bd-fae3-4684-ac5d-120fdadf6acd.png)

**Comment by juliarvalenti** [comment]
Nevermind - false alarm.  This was a case of Docker not creating new images because they're both 0.8.0.  I deleted the old images, ran docker-compose again, and everything is working now.
