### ISSUE TITLE
dbt ingestion fails for test case results with invalid column name

### ISSUE THREAD

**Issue by finite1** [open-metadata/OpenMetadata#24636]
**Affected module**
dbt ingestion 

**Describe the bug**
Bug is described here https://github.com/open-metadata/OpenMetadata/issues/23891 and was fixed for snowflake. The same happens with Unity Catalog. In some cases it also doesn't find the columns even though they have proper capitalization both for the tests as well as in open metadata. 

This case is where all column names match the column name in OM:
`[2025-11-11 19:05:45] WARNING  {metadata.Ingestion:status:95} - Failed to ingest CreateTestCaseRequest [relationships_un_rueckerstattungen_medis_base_PersonNr__PartnerNr__ref_un_person_base_] due to api request failure: Invalid column name PersonNr`
PersonNr is in table un_rueckerstattungen.... und PartnerNr is in un_person_base

This is a case where Position in OM is capitalized and it fails:
`Failed to ingest CreateTestCaseRequest [unique_un_abrechnungsposition_cur_dp_AbrechnungspositionHK] due to api request failure: Invalid column name dp_AbrechnungspositionHK`

**To Reproduce**

dbt ingestion with unity catalog. If helpful I can provide logs. 

**Expected behavior**
dbt ingestion is not case sensitive for unity catalog as well. 

**Version:**
 - Python version: 3.11
 - OpenMetadata version: 1.10.8
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[dbt]==1.10.8`]

**Additional context**

**Comment by JohnsonK1118** [comment]
Thanks @finite1 for filling out this issue, really looking forward to adding this new feature into OpenMetadata, in the meantime the best way to keep track of all the latest updates is by bookmarking [OpenMetadata](https://github.com/open-metadata/OpenMetadata) with a star!

And if you haven’t already, I'd like to invite you to join our upcoming virtual community meetup next Wednesday. We’ll be sharing the OMD Q1 roadmap along with a community spotlight featuring real-world use cases from Wix. Hope to see you there!

**Comment by edg956** [comment]
Hi @finite1 from your description I derived the following simplified `schema.yml`

```yml
version: 2

models:
  - name: un_person_base
    columns:
      - name: PartnerNr

  - name: un_rueckerstattungen_medis_base
    columns:
      - name: PersonNr
        data_tests:
          - relationships:
              to: ref('un_person_base')
              field: PartnerNr
```

Which I used to reproduce your issue. I have a solution for it, but could you please confirm your schema looks something like this?

This should also mean that in your `manifest.json`, the entry for `relationships_un_rueckerstattungen_medis_base_PersonNr__PartnerNr__ref_un_person_base_` should specify the dependency on those two tables.

**Comment by finite1** [comment]
@edg956 hey, the model un_rueckerstattungen_medis_base is correct. However, we do not define a model for un_person_base. I asked our data engineers why that is. Apparently since there are no tests for this model and the docs for the columns can be derived from our other layers, an entry in our schema.yml is not necessary. 

I'm unsure if this might be the reason why test case ingestion fails, though I'm pretty sure that the issues we have with ingestion isn't always for models that aren't present in our yml files. I can try and confirm if you need. 

The entry in manifest.json does therefore also not have a filepath for the un_person_base model. So I could see how that is connected.

**Comment by edg956** [comment]
@finite1 Got it. I'll try to reproduce it with that set up. Could you please send me here the entry in the manifest.json for this test? can be simplified to keep only the relevant information

**Comment by finite1** [comment]
@edg956 Decided to just include the full test so everything is there. Also noticed that both tables are mentioned in `refs` field

``` 
"name": "relationships_un_rueckerstattungen_medis_base_PersonNr__PartnerNr__ref_un_person_base_", "resource_type": "test", "package_name": "dp", "path": "relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e.sql", "original_file_path": "models/2_un/risikoausgleich/2_un_risikoausgleich.yml", "unique_id": "test.dp.relationships_un_rueckerstattungen_medis_base_PersonNr__PartnerNr__ref_un_person_base_.506cfcbc79", "fqn": ["dp", "2_un", "risikoausgleich", "relationships_un_rueckerstattungen_medis_base_PersonNr__PartnerNr__ref_un_person_base_"], "alias": "relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e","checksum": {"name": "none", "checksum": ""}, "config": {"enabled": true, "alias": "relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e","schema": "dbt_test__audit", "database": null, "tags": [], "meta": {}, "group": null, "materialized": "test", "severity": "ERROR", "store_failures": null, "store_failures_as": null, "where": null, "limit": null, "fail_calc": "count(*)","warn_if": "!= 0", "error_if": "!= 0"}, "tags": [], "description": "", "columns": {}, "meta": {}, "group": null, "docs": {"show": true, "node_color": null}, "patch_path": null, "build_path": null,"unrendered_config": {"alias": "relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e"}, "created_at": 1775920177.2761164, "relation_name": null,"raw_code": "{{ test_relationships(**_dbt_generic_test_kwargs) }}{{ config(alias=\"relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e\") }}", "doc_blocks": [], "language": "sql",
"refs": [{"name": "un_person_base", "package": null, "version": null}, {"name": "un_rueckerstattungen_medis_base", "package": null, "version": null}], "sources": [], "metrics": [],"depends_on": {"macros": ["macro.dbt.test_relationships", "macro.dbt.get_where_subquery"], "nodes": ["model.dp.un_person_base", "model.dp.un_rueckerstattungen_medis_base"]}, "compiled_path": "target/compiled/dp/models/2_un/risikoausgleich/2_un_risikoausgleich.yml/relationships_un_rueckerstattu_08022abe13e5f829dea7ebafbf3a444e.sql", "compiled": true, "compiled_code": "\n    \n    \n\nwith child as (\n    select PersonNr as from_field\n    from `fab_unified`.`risikoausgleich`.`un_rueckerstattungen_medis_base`\n    where PersonNr is not null\n),\n\nparent as (\n    select PartnerNr as to_field\n    from `fab_unified`.`partner`.`un_person_base`\n)\n\nselect\n    from_field\n\nfrom child\nleft join parent\n    on child.from_field = parent.to_field\n\nwhere parent.to_field is null\n\n\n","extra_ctes_injected": true,"extra_ctes": [], "contract": {"enforced": false, "alias_types": true, "checksum": null}, "column_name": "PersonNr", "file_key_name": "models.un_rueckerstattungen_medis_base", "attached_node": "model.dp.un_rueckerstattungen_medis_base","test_metadata": {"name": "relationships", "kwargs": {"column_name": "PersonNr", "to": "ref('un_person_base')", "field": "PartnerNr", "model": "{{ get_where_subquery(ref('un_rueckerstattungen_medis_base')) }}"}, "namespace": null}},
```

**Comment by edg956** [comment]
@finite1 yeah I see the `depends_on` key references both tables. It's likely this is the source. You can check my related PR addresses this to choose the right table from `depends_on` in order to create the test, instead of blindly using all tables.

The system attempted to create a column test case for `un_person_base` with the column `PersonNr`. It seems it wrongly picked that table because it used everything in `depends_on`.

**Comment by edg956** [comment]
@finite1 I've merged my PR. These fixes will go into 1.12.6. If you're able to test them and report back any issue I'd appreciate it

**Comment by finite1** [comment]
@edg956 I was able to upgrade to latest and ingest our dbt models again. From what I can tell we got fewer failed test case creations, but some still persist. I will analyze further and would update you with more information asap, most likely next week or so. Hope this is ok.
