### ISSUE TITLE
[REDSHIFT] Query Parsing Issue

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#2575]
### Affected module
impact Ingestion Framework

### Description

1. while parsing the  query 
    ```
    SELECT DISTINCT T.ret_field
    FROM
        Hashes
        INNER JOIN LATERAL
        (
            SELECT table.ret_field
            FROM table
            WHERE
                table.phash = Hashes.phash
                AND table.last_seen BETWEEN '2015-10-01 00:00:00' AND '2015-10-31 23:59:59'
        ) AS T ON true
    ```
    the [table_usage](https://github.com/open-metadata/OpenMetadata/blob/60aa5f39396d1fa03332e292432790ee5b16b0c5/ingestion/src/metadata/ingestion/stage/table_usage.py#L117) dictionary contains following data 
    
    Table Name | Count 
    --- | ---
    Hashes | 1
    LATERAL | 1
    table | 1
    WHERE | 1
    
    `LATERAL` and `WHERE` are the keywords and should not be included in this dictionary 
2. Redshift recursive query is not getting parsed.
    ```
    with recursive org_cte(id, name, manager_id, level) as
    ( select id, name, manager_id, 1 as level
      from employee
      where name = 'John'
      union all
      select e.id, e.name, e.manager_id, level + 1
      from employee e, john_org j
      where e.manager_id = j.id and level < 4 
      )
     select id, name, manager_id from org_cte order by manager_id;
    ```
### To Reproduce
Queries can be added to file `ingestion/examples/sample_data/datasets/query_log` and tested by ingesting [sample_usage](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/pipelines/sample_usage.json) 

### Additional context
Issue Identified in #2510

**Comment by harshach** [comment]
@ulixius9 I think the first part is ok although we should fix it somepoint. But having those there will not give us a exact match of the table
whats the error you are getting on the second query, can you paste it here

**Comment by ulixius9** [comment]
@harshach didn't get any error for the 2nd part, when I put just the 2nd query in [query_log](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/tests/unit/resources/datasets/query_log) and log [workflow.stage.table_usage](https://github.com/open-metadata/OpenMetadata/blob/4abede9f9ddc9a0a16c14b34c072f1ce0e2cd115/ingestion/tests/unit/test_query_parser.py#L93) dictionary, the output is an empty dictionary so the query is not getting processed by the parser

**Comment by pmbrull** [comment]
@harshach tested the parsing manually using `sqllineage` and the issue is still there.
For the first query, the parsing fails.
For the second, no table data is being picked up.
We might need to handle this at the library itself

**Comment by harshach** [comment]
@nahuelverdugo @mohityadav766 are we going to handle in 0.13.1

**Comment by pmbrull** [comment]
Will be fixed once we move to the new sqllineage
